/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package calculatormain;

/**
 *
 * @author balah.muhammad
 */
public class Calc extends javax.swing.JFrame {

    /**
     * Creates new form Calc
     */
    public Calc() {
        initComponents();
    }

    
    private double operand1;
    private double operand2;
    private double total;
    
    private String answer;
    private String action;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        mainText = new javax.swing.JTextField();
        operatorClear = new javax.swing.JButton();
        operatorPlusMinus = new javax.swing.JButton();
        operatorDivide = new javax.swing.JButton();
        operatorMultiply = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        operatorMinus = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        operatorPlus = new javax.swing.JButton();
        num1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        numDecimal = new javax.swing.JButton();
        operatorEquals = new javax.swing.JButton();

        jButton16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton16.setText("jButton1");
        jButton16.setPreferredSize(new java.awt.Dimension(100, 60));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton17.setText("jButton1");
        jButton17.setPreferredSize(new java.awt.Dimension(100, 60));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainText.setBackground(new java.awt.Color(0, 255, 255));
        mainText.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        mainText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        mainText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainTextActionPerformed(evt);
            }
        });

        operatorClear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        operatorClear.setText("c");
        operatorClear.setPreferredSize(new java.awt.Dimension(100, 60));
        operatorClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorClearActionPerformed(evt);
            }
        });

        operatorPlusMinus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        operatorPlusMinus.setText("+/-");
        operatorPlusMinus.setPreferredSize(new java.awt.Dimension(100, 60));

        operatorDivide.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        operatorDivide.setText("/");
        operatorDivide.setPreferredSize(new java.awt.Dimension(100, 60));
        operatorDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorDivideActionPerformed(evt);
            }
        });

        operatorMultiply.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        operatorMultiply.setText("*");
        operatorMultiply.setPreferredSize(new java.awt.Dimension(100, 60));
        operatorMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorMultiplyActionPerformed(evt);
            }
        });

        num8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        num8.setText("8");
        num8.setPreferredSize(new java.awt.Dimension(100, 60));
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });

        num9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        num9.setText("9");
        num9.setPreferredSize(new java.awt.Dimension(100, 60));
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });

        operatorMinus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        operatorMinus.setText("-");
        operatorMinus.setPreferredSize(new java.awt.Dimension(100, 60));
        operatorMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorMinusActionPerformed(evt);
            }
        });

        num7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        num7.setText("7");
        num7.setPreferredSize(new java.awt.Dimension(100, 60));
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });

        num4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        num4.setText("4");
        num4.setPreferredSize(new java.awt.Dimension(100, 60));
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });

        num5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        num5.setText("5");
        num5.setPreferredSize(new java.awt.Dimension(100, 60));
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });

        num6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        num6.setText("6");
        num6.setPreferredSize(new java.awt.Dimension(100, 60));
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });

        operatorPlus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        operatorPlus.setText("+");
        operatorPlus.setPreferredSize(new java.awt.Dimension(100, 60));
        operatorPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorPlusActionPerformed(evt);
            }
        });

        num1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        num1.setText("1");
        num1.setPreferredSize(new java.awt.Dimension(100, 60));
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });

        num2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        num2.setText("2");
        num2.setPreferredSize(new java.awt.Dimension(100, 60));
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });

        num3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        num3.setText("3");
        num3.setPreferredSize(new java.awt.Dimension(100, 60));
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });

        num0.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        num0.setText("0");
        num0.setPreferredSize(new java.awt.Dimension(100, 60));

        numDecimal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        numDecimal.setText(".");
        numDecimal.setPreferredSize(new java.awt.Dimension(100, 60));
        numDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numDecimalActionPerformed(evt);
            }
        });

        operatorEquals.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        operatorEquals.setText("=");
        operatorEquals.setPreferredSize(new java.awt.Dimension(100, 60));
        operatorEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorEqualsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainText)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(operatorClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(operatorPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(num0, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(operatorDivide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(operatorEquals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(operatorPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(operatorMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(operatorMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainText, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(operatorClear, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operatorPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operatorDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operatorMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operatorMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operatorPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num0, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(operatorEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        String number = mainText.getText()+ num4.getText();
        mainText.setText(number);
    }//GEN-LAST:event_num4ActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
        String number = mainText.getText()+ num6.getText();
        mainText.setText(number);
    }//GEN-LAST:event_num6ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        String number = mainText.getText()+ num6.getText();
        mainText.setText(number);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void operatorEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operatorEqualsActionPerformed
        operand2 = Double.parseDouble(mainText.getText());
        if (action.equals("+"))  {
            total = operand1 + operand2;
            answer = String.format("%.2f", total);
        }
        else if (action.equals("-")) {
            total = operand1 - operand2;
            answer = String.format("%.2f", total);
        }     
        else if (action.equals("*")) {
            total = operand1 * operand2;
            answer = String.format("%.2f", total);
        }
        else if (action.equals ("/")) {
            total = operand1 / operand2;
            answer = String.format("%.2f", total);
        }
        mainText.setText(answer);
        
    }//GEN-LAST:event_operatorEqualsActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        String number = mainText.getText()+ num2.getText();
        mainText.setText(number);
    }//GEN-LAST:event_num2ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        String number = mainText.getText()+ num5.getText();
        mainText.setText(number);
    }//GEN-LAST:event_num5ActionPerformed

    private void numDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numDecimalActionPerformed
        String number = mainText.getText()+ numDecimal.getText();
        mainText.setText(number);
    }//GEN-LAST:event_numDecimalActionPerformed

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        String number = mainText.getText()+ num1.getText();
        mainText.setText(number);
    }//GEN-LAST:event_num1ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
       String number = mainText.getText()+ num3.getText();
        mainText.setText(number);
    }//GEN-LAST:event_num3ActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
        String number = mainText.getText()+ num7.getText();
        mainText.setText(number);
    }//GEN-LAST:event_num7ActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
        String number = mainText.getText()+ num8.getText();
        mainText.setText(number);
    }//GEN-LAST:event_num8ActionPerformed

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
        String number = mainText.getText()+ num9.getText();
        mainText.setText(number);
    }//GEN-LAST:event_num9ActionPerformed

    private void operatorClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operatorClearActionPerformed
        String number = "";
        mainText.setText(number);   
    }//GEN-LAST:event_operatorClearActionPerformed

    private void mainTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainTextActionPerformed

    private void operatorPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operatorPlusActionPerformed
        operand1 = Double.parseDouble(mainText.getText());
        mainText.setText("");
        action = "+";
    }//GEN-LAST:event_operatorPlusActionPerformed

    private void operatorMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operatorMinusActionPerformed
                operand1 = Double.parseDouble(mainText.getText());
        mainText.setText("");
        action = "-";
    }//GEN-LAST:event_operatorMinusActionPerformed

    private void operatorMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operatorMultiplyActionPerformed
                operand1 = Double.parseDouble(mainText.getText());
        mainText.setText("");
        action = "*";
    }//GEN-LAST:event_operatorMultiplyActionPerformed

    private void operatorDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operatorDivideActionPerformed
                operand1 = Double.parseDouble(mainText.getText());
        mainText.setText("");
        action = "/";
    }//GEN-LAST:event_operatorDivideActionPerformed
    
    
    
    {
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JTextField mainText;
    private javax.swing.JButton num0;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JButton numDecimal;
    private javax.swing.JButton operatorClear;
    private javax.swing.JButton operatorDivide;
    private javax.swing.JButton operatorEquals;
    private javax.swing.JButton operatorMinus;
    private javax.swing.JButton operatorMultiply;
    private javax.swing.JButton operatorPlus;
    private javax.swing.JButton operatorPlusMinus;
    // End of variables declaration//GEN-END:variables
}
